apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: cloud-project
spec:
  selector:
    app: rabbitmq
  ports:
    - name: broker
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 31672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 32672
  type: NodePort
