apiVersion: v1
kind: Service
metadata:
  name: node-red
  namespace: cloud-project
spec:
  selector:
    app: node-red
  ports:
    - protocol: TCP
      port: 1880
      targetPort: 1880
  type: NodePort
