apiVersion: v1
kind: Service
metadata:
  name: portainer
  namespace: cloud-project
spec:
  type: NodePort
  selector:
    app: portainer
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 32700
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer
  namespace: cloud-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portainer
  template:
    metadata:
      labels:
        app: portainer
    spec:
      containers:
      - name: portainer
        image: portainer/portainer-ce:latest
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: portainer-data
          mountPath: /data
      volumes:
      - name: portainer-data
        emptyDir: {}

