apiVersion: v1
kind: Service
metadata:
  name: thingsboard
  namespace: cloud-project
spec:
  selector:
    app: thingsboard
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32600
  type: NodePort
