apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: cloud-project
spec:
  selector:
    app: minio
  ports:
    - name: api-port
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 31522
    - name: webui-port
      protocol: TCP
      port: 9001
      targetPort: 9001
      nodePort: 32500
  type: NodePort
